"""Shared Pydantic models, enumerations, and primitive types.

This module defines the small set of value-typed primitives that every other
module in :mod:`regclock` builds on. Keeping them in one place ensures the
data contract is single-sourced and that any future change to a controlled
vocabulary (e.g. adding a lifecycle state) is a one-line patch.
"""

from __future__ import annotations

from enum import Enum


class State(str, Enum):
    """The deterministic lifecycle states an obligation instance may be in.

    Transitions are implemented in :mod:`regclock.lifecycle.state_machine`.

    Members:
        PENDING: Obligation is known but its trigger has not yet fired.
        UPCOMING: Trigger fired; due date is in the future.
        DUE: Due date is today (or inside the configured "due window").
        OVERDUE: Due date has passed and no satisfying evidence is on record.
        SATISFIED: Required action has been performed and evidenced in time
            (or during a configured grace period).
        WAIVED: A competent authority or amendment has waived this instance.
        UNDETERMINED: Applicability or trigger status cannot be decided from
            the inputs available. The engine never guesses; it surfaces this.
    """

    PENDING = "pending"
    UPCOMING = "upcoming"
    DUE = "due"
    OVERDUE = "overdue"
    SATISFIED = "satisfied"
    WAIVED = "waived"
    UNDETERMINED = "undetermined"


class DeadlineKind(str, Enum):
    """How a deadline is anchored in calendar time.

    Members:
        RELATIVE: "Within N (business|calendar) days of the trigger event."
        ABSOLUTE: A fixed date or month-day each year, e.g. "by 31 March".
        RECURRING: Generated by a recurrence rule (e.g. quarterly).
        ON_DEMAND: No fixed due date until the obligation is triggered, then
            becomes relative.
    """

    RELATIVE = "relative"
    ABSOLUTE = "absolute"
    RECURRING = "recurring"
    ON_DEMAND = "on_demand"


class DayBasis(str, Enum):
    """Whether N-day offsets count business days or raw calendar days.

    Members:
        BUSINESS: Skip weekends and jurisdiction holidays.
        CALENDAR: Count every day, including weekends and holidays.
    """

    BUSINESS = "business"
    CALENDAR = "calendar"


class RecurrenceFreq(str, Enum):
    """Coarse recurrence frequencies supported by the lightweight engine.

    For anything more exotic (e.g. "second Tuesday of every other month")
    callers should provide an explicit list of absolute dates via
    :class:`regclock.model.recurrence.ExplicitDates` instead.
    """

    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"
    QUARTERLY = "quarterly"
    ANNUALLY = "annually"


class EventKind(str, Enum):
    """Kinds of events that can appear on the replayable event log.

    Members:
        TRIGGER: The obligation's triggering condition has occurred.
        ACTION: The required action has been performed.
        EVIDENCE: Supporting evidence has been recorded.
        WAIVER: The obligation instance has been waived.
        AMENDMENT: The obligation definition itself has been amended.
    """

    TRIGGER = "trigger"
    ACTION = "action"
    EVIDENCE = "evidence"
    WAIVER = "waiver"
    AMENDMENT = "amendment"
