"""Internationalisation (i18n) registry for display strings and templates.

regclock keeps machine-readable values (enum ``.value``, JSON event-log
keys, evidence-pack digests, scheduled-instance identifiers) in
**English/ASCII** so that serialised artefacts remain interoperable
across locales. Only *display* strings — labels in reports, headings
in filing stubs, reminder bodies — are translated.

Two things are translatable:

* **labels** — a flat ``dict[str, str]`` keyed by dotted names
  (e.g. ``"ui.bearer"``, ``"state.satisfied"``). Looked up at render
  time via :func:`t`, :func:`label_for_state`, and
  :func:`label_for_event_kind`.
* **templates** — Jinja2 ``.md.j2`` / ``.html.j2`` files. The default
  pack lives under ``regclock/templates/en/``. Language packs can ship
  their own templates by registering a directory via
  :func:`register_language`; missing template names fall back to the
  English pack.

Usage:

    >>> from regclock import i18n
    >>> i18n.register_language("es", labels={
    ...     "ui.bearer": "Sujeto obligado",
    ...     "state.satisfied": "Cumplida",
    ...     ...
    ... })
    >>> i18n.set_default_language("es")
    >>> # or pass lang="es" explicitly to render functions

Anything not registered falls back to English, then to the key itself.
The fallback is loud-by-design only for missing translations (returns
the raw key), so missing strings are visible to translators.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from regclock.schemas.types import EventKind, State


DEFAULT_LANG = "en"


_BUILTIN_LABELS_EN: dict[str, str] = {
    "state.pending": "Pending",
    "state.upcoming": "Upcoming",
    "state.due": "Due",
    "state.overdue": "Overdue",
    "state.satisfied": "Satisfied",
    "state.waived": "Waived",
    "state.undetermined": "Undetermined",
    "event_kind.trigger": "Trigger",
    "event_kind.action": "Action",
    "event_kind.evidence": "Evidence",
    "event_kind.waiver": "Waiver",
    "event_kind.amendment": "Amendment",
    "ui.filing_stub_title": "Filing stub",
    "ui.bearer": "Bearer",
    "ui.jurisdiction": "Jurisdiction",
    "ui.source": "Source",
    "ui.due_on": "Due on",
    "ui.current_state": "Current state",
    "ui.required_action": "Required action",
    "ui.acceptable_evidence": "Acceptable evidence",
    "ui.consequence_on_violation": "Consequence on violation",
    "ui.stub_disclaimer": (
        "This stub was generated by regclock. "
        "It is a working aid, not a legal filing."
    ),
    "ui.reminder_heads_up": "Heads-up",
    "ui.reminder_due_date": "Due date",
    "ui.reminder_day_unit": "day(s) from",
    "ui.reminder_what_to_do": "What to do",
    "ui.reminder_evidence_kinds": "What counts as evidence",
    "report.col_obligation": "Obligation",
    "report.col_title": "Title",
    "report.col_jurisdiction": "Jurisdiction",
    "report.col_due": "Due",
    "report.col_state": "State",
    "report.col_days": "Days",
    "report.col_evidence": "Evidence",
}


_LABELS: dict[str, dict[str, str]] = {"en": dict(_BUILTIN_LABELS_EN)}
_TEMPLATE_DIRS: dict[str, Path] = {}
_default_lang: str = DEFAULT_LANG


def register_language(
    lang: str,
    labels: dict[str, str],
    templates_dir: Path | str | None = None,
) -> None:
    """Register (or extend) a language pack at runtime.

    Args:
        lang: ISO 639-1 code (e.g. ``"es"``, ``"zh"``). Stored
            lower-cased.
        labels: Flat ``key -> translated string`` mapping. Missing keys
            fall back to English at lookup time. Calling this twice for
            the same language **merges** keys (later wins).
        templates_dir: Optional path to a directory containing
            translated Jinja templates. File names must match the
            English pack (``filing_stub.md.j2``,
            ``reminder_body.md.j2``); missing files fall back to the
            English template.

    Example:
        >>> register_language("es", {"ui.bearer": "Sujeto obligado"})

    """
    lang = lang.lower()
    bucket = _LABELS.setdefault(lang, {})
    bucket.update(labels)
    if templates_dir is not None:
        _TEMPLATE_DIRS[lang] = Path(templates_dir)


def set_default_language(lang: str) -> None:
    """Set the default language used when no ``lang`` is passed at call sites."""
    global _default_lang
    _default_lang = lang.lower()


def get_default_language() -> str:
    """Return the current default language code."""
    return _default_lang


def available_languages() -> list[str]:
    """List language codes with at least one registered label."""
    return sorted(_LABELS.keys())


def t(key: str, lang: str | None = None) -> str:
    """Look up a display string.

    Resolution order: requested language → English → the key itself
    (so untranslated keys remain visible to translators rather than
    failing silently).

    Args:
        key: Dotted label key, e.g. ``"ui.bearer"`` or
            ``"state.satisfied"``.
        lang: Language code; defaults to the current default language.

    Returns:
        The translated string, or the key as a placeholder when no
        translation is registered in any language.

    """
    lang = (lang or _default_lang).lower()
    if (val := _LABELS.get(lang, {}).get(key)) is not None:
        return val
    if (val := _LABELS["en"].get(key)) is not None:
        return val
    return key


def label_for_state(state: State, lang: str | None = None) -> str:
    """Translate a :class:`State` enum member for display.

    The enum's ``.value`` itself is never translated; this returns the
    *display* string only. JSON serialisation continues to use
    ``state.value`` (e.g. ``"satisfied"``).
    """
    return t(f"state.{state.value}", lang)


def label_for_event_kind(kind: EventKind, lang: str | None = None) -> str:
    """Translate an :class:`EventKind` enum member for display."""
    return t(f"event_kind.{kind.value}", lang)


def templates_dir_for(lang: str) -> Path | None:
    """Return the registered templates directory for ``lang`` if any.

    Returns ``None`` when the language has no custom template directory
    (callers should then fall back to the English template pack).
    """
    return _TEMPLATE_DIRS.get(lang.lower())


def labels_for_jinja(lang: str | None = None) -> dict[str, str]:
    """Return the label dict for use as a Jinja ``ui`` namespace.

    Keys with the ``ui.`` prefix are exposed without the prefix so
    templates can write ``{{ ui.bearer }}`` instead of
    ``{{ ui['ui.bearer'] }}``. Other namespaces (``state.``,
    ``event_kind.``, ``report.``) are exposed via the helper
    functions registered as Jinja globals.
    """
    lang = (lang or _default_lang).lower()
    merged: dict[str, str] = {}
    merged.update(_LABELS["en"])
    merged.update(_LABELS.get(lang, {}))
    return {
        key.removeprefix("ui."): value
        for key, value in merged.items()
        if key.startswith("ui.")
    }


__all__ = [
    "DEFAULT_LANG",
    "available_languages",
    "get_default_language",
    "label_for_event_kind",
    "label_for_state",
    "labels_for_jinja",
    "register_language",
    "set_default_language",
    "t",
    "templates_dir_for",
]
